# Generated by Django 4.0 on 2024-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwyl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oridata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
