# Generated by Django 4.0 on 2024-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwyl', '0002_oridata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_keyword', models.CharField(max_length=256)),
                ('q_doclist', models.TextField()),
            ],
        ),
    ]
