# Generated by Django 4.0 on 2024-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwyl', '0003_odindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_url', models.CharField(max_length=256)),
                ('movie_title', models.CharField(max_length=64)),
                ('movie_keywords', models.TextField()),
                ('movie_description', models.TextField()),
                ('movie_directors', models.TextField()),
                ('movie_actors', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoubanMovieIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_keyword', models.CharField(max_length=256)),
                ('movie_doclist', models.TextField()),
            ],
        ),
    ]
