# Generated by Django 4.0 on 2024-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwyl', '0004_doubanmovie_doubanmovieindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_keyword', models.CharField(max_length=256)),
                ('q_doclist', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lessdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
