# Generated by Django 4.0 on 2024-06-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwyl', '0005_ldindex_lessdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoubanMovie',
        ),
        migrations.DeleteModel(
            name='DoubanMovieIndex',
        ),
        migrations.DeleteModel(
            name='LDIndex',
        ),
        migrations.DeleteModel(
            name='lessdata',
        ),
    ]
